import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import PageHeader from '../components/layout/PageHeader';
import Card from '../components/common/Card';
import Button from '../components/common/Button';
import Badge from '../components/common/Badge';
import Loader from '../components/common/Loader';
import EmptyState from '../components/common/EmptyState';
import RequirementList from '../components/jobs/RequirementList.jsx';
import ResumeUploader from '../components/resumes/ResumeUploader';
import CandidateTable from '../components/candidates/CandidateTable';
import { jobService } from '../services/jobService';
import { candidateService } from '../services/candidateService';
import { useAsync } from '../hooks/useAsync';
import { formatDate } from '../utils/formatters';

export default function JobDetailPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [feedback, setFeedback] = useState('');

  const job = useAsync(() => jobService.getById(id), [id]);
  const candidates = useAsync(() => candidateService.listByJob(id), [id]);

  const handleScreened = (candidate) => {
    setFeedback(`${candidate.name} screened — score ${candidate.score}/100`);
    candidates.reload();
  };

  const handleStatusChange = async (candidateId, status) => {
    await candidateService.updateStatus(candidateId, status);
    candidates.reload();
  };

  if (job.loading) return <Loader label="Loading job…" />;
  if (job.error) return <div className="alert alert--error">{job.error}</div>;

  const j = job.data;

  return (
    <>
      <PageHeader
        breadcrumb="Jobs / Details"
        title={j.title}
        subtitle={`${j.department || '—'} • ${j.location || '—'} • ${j.employmentType}`}
        actions={
          <>
            <Button variant="ghost" onClick={() => navigate(`/jobs/${j.id}/edit`)}>Edit</Button>
            <Button onClick={() => navigate('/jobs')}>Back to Jobs</Button>
          </>
        }
      />

      {feedback && <div className="alert alert--success">{feedback}</div>}

      <div className="grid grid--2-1" style={{ marginBottom: 22 }}>
        <Card title="Job Description" subtitle={`Posted ${formatDate(j.createdAt)}`}>
          <div className="jd">
            {j.description.split('\n').map((line, i) => (
              <p key={i}>{line || '\u00A0'}</p>
            ))}
          </div>
        </Card>

        <Card
          title="Extracted Requirements"
          subtitle="Auto-generated by the ATS engine"
          actions={<Badge tone={j.status === 'Open' ? 'success' : 'neutral'}>{j.status}</Badge>}
        >
          <RequirementList requirements={j.requirements} />
        </Card>
      </div>

      <Card
        title="Upload Resumes"
        subtitle="Upload .txt resumes or paste resume text to parse and score instantly"
        className="mb-22"
      >
        <ResumeUploader jobId={j.id} onScreened={handleScreened} />
      </Card>

      <Card
        title="Screening Results"
        subtitle={`${candidates.data?.length ?? 0} candidate(s) screened for this role`}
      >
        {candidates.loading ? (
          <Loader />
        ) : candidates.data?.length ? (
          <CandidateTable
            candidates={candidates.data}
            onOpen={(cid) => navigate(`/candidates/${cid}`)}
            onStatusChange={handleStatusChange}
          />
        ) : (
          <EmptyState
            icon="📄"
            title="No resumes screened yet"
            description="Upload resumes above — each one is parsed and scored against this job's requirements."
          />
        )}
      </Card>
    </>
  );
}